server:
  port: 8088
configurables:
  poa-url: http://localhost:8080/power-of-attorneys/
  debit-card-url: http://localhost:8080/debit-cards/
  credit-card-url: http://localhost:8080/credit-cards/
  account-url: http://localhost:8080/accounts/
